CREATE TABLE IF NOT EXISTS
    authors(id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    birth_year VARCHAR(50) NOT NULL,
    country VARCHAR(50) NOT NULL);


CREATE TABLE IF NOT EXISTS
    Books(id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    name VARCHAR(50) NOT NULL,
    category VARCHAR(50) NOT NULL,
    cover VARCHAR(50) NOT NULL,
    author VARCHAR(50) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    published_at TIMESTAMPTZ NOT NULL DEFAULT NOW();
